import type { Metadata } from 'next';
import './globals.css';
import { Onest } from 'next/font/google';

const onest = Onest({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-onest'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${onest.variable}`}>
      <body>
        <div className="mx-auto max-w-[56rem] min-h-screen p-24 ">{children}</div>
      </body>
    </html>
  );
}
